rollbar/rollbar-php-laravel

src/RollbarServiceProvider.php
When rollbar is **NOT** configured, it's services isn't registered, but it's invoked whenever there's an exception in the application since it's still booted and always listen to log events, and thus we get the following exception (this PR avoids that exception):
```
(1/1) BindingResolutionException
Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class Rollbar\RollbarLogger
```
Exception stack:
```
in Container.php (line 933)
at Container->unresolvablePrimitive(object(ReflectionParameter))
in Container.php (line 871)
at Container->resolvePrimitive(object(ReflectionParameter))
in Container.php (line 812)
at Container->resolveDependencies(array(object(ReflectionParameter)))
in Container.php (line 779)
at Container->build('Rollbar\\RollbarLogger')
in …
```
=> Don't boot rollbar if it is not configured.

src/RollbarLogHandler.php, tests/RollbarTest.php
This PR fixes the broken `person_fn` as reported in #1 and #3, but
as they seem pretty old inactive PRs with broken tests, I thought I'd
submit a new one that can hopefully be merged soon, as this bug is
stopping us from upgrading to the newer versions of this library.
I decided to go for the safest option, which is to revert to the old existing
logic when `person_fn` still worked.
Currently, when the session is not empty, this package always sets a
`person` entry in the rollbar config, which results in the rollbar/rollbar
package never caling the `person_fn`.
The rollbar/rollbar package only calls `$config['person_fn']` when the
`$config['person']` doesn't already exist, which as stated above, will
always be set when the session is not empty.
Revert back to the behaviour originally found …
=> Fix person_fn not being called when session not empty

src/RollbarServiceProvider.php
This will helps prevent errors during a first deploy in some cases(e.g.: if the .env file has not been setup until later in the process).
=> Prevent boot/register if $level == none

src/RollbarServiceProvider.php
This is a reopened PR for an accidentally closed PR https://github.com/rollbar/rollbar-php-laravel/pull/11
=> Prevent boot/register if $level == none (reopened)

src/RollbarServiceProvider.php
In the boot method, we check for the `access_token` variable, but when checking when to register or not we're checking for the `token` variable. This ensures the same variable is checked.
=> Check the correct token to ensure if we need to register

src/RollbarServiceProvider.php
As per the official documentation, the parameter for the token on the logging config file should be called `access_token`. However, without this fix, you need to have both `access_token` and `token` set to the same value, under `logging.channels.rollbar`. Otherwise, it will not work.
This adds another hotfix to replace the `$key`, when its value is `"token"`, with `"access_token"`.
P.S. As an alternative, you could also replace the line: `$token = static::config('token');` with `$token = static::config('access_token');`, just so we don't add another if. I'll leave the authors to decide which is best.
----
Later edit: I went ahead and created a new commit to remove the extra if and fix the actual bug. But feel free to use either of the versions.
=> Fixed the access_token config getter function.

src/MonologHandler.php
=> Properly handle Laravel model for "person_fn".

composer.json, src/RollbarServiceProvider.php, tests/RollbarTest.php
Makes it possible to install this package on Laravel 6
=> Laravel 6 compatibility

.gitignore, src/AgentHandler.php, src/RollbarServiceProvider.php, tests/RollbarTest.php
The configuration for logging in Laravel requires an instance of [`Monolog\Handler\HandlerInterface`][1], but the Rollbar library requires a string with value of "agent" to use the agent. This disconnect makes it impossible to use the Rollbar agent with Laravel.
Fixes Issue #85, by way of an adapter class. An example Laravel configuration to use the adapter:
```
'rollbar' => [
'driver' => 'monolog',
'handler' => \Rollbar\Laravel\AgentHandler::class,
'level' => 'debug',
'access_token' => env('ROLLBAR_TOKEN'),
'environment' => 'production'
],
```
[1]:https://github.com/Seldaek/monolog/blob/main/src/Monolog/Handler/HandlerInterface.php
> Fixes Issue #85.
=> Add support for rollbar-agent

src/MonologHandler.php
this fix was originally proposed on issue https://github.com/rollbar/rollbar-php-laravel/issues/83 and PR https://github.com/rollbar/rollbar-php-laravel/pull/84 and https://github.com/rollbar/rollbar-php-laravel/pull/90 without further interaction/response from the original contributor.
> Fix [#83](), [#84]() and [#90]()
=> fixed compatibility with Lumen 8.x without sessions

src/MonologHandler.php
Hello,
I just implemented this package into my project and my primary key is not `id`, so this means the `person_fn` key in the config will not work for me because it looks at the `id` attribute. 
So I added a fallback on the function of Laravel: `getKey()`, this will look at if the `$primaryKey` name is changed inside the modal else will send the value from the `id` attribute.  
If you have any question feel free to ask.
=> Added fallback on getKey method.

.github/workflows/ci-2.x.yml, .github/workflows/ci-4.x.yml, .github/workflows/ci.yml
We integrate with Laravel versions 5.5+. The existing tests verify unit functionality with [TestBench][1] but has a few caveats. First, it tests the package against the latest version of Laravel on the PHP engine running the test. Second, as written, there was no version constraint for testbench 3, which is the only way to get Laravel 5 tests. Third, the tests do not perform an end to end test of actual logging within a Laravel application. Finally, the tests do not cover Laravel Zero or Lumen (or Nova, for that matter).
The drawback with this architecture is that changes meant to be backwards compatible could only be verified by manually changing composer JSON and, in the case of PHP engine compatibility, by running with engine alternatives. Additionally, if the package had side effects …
=> feat: add Laravel integration test matrix

.github/workflows/ci.yml, composer.json
Adds Laravel 9 Support to CI actions and composer
=> Laravel 9 Support

.github/workflows/ci.yml
Laravel 6 and 7 requires PHP 7.2 - 8.0, so exclude all PHP versions after 8.1 on GitHub Actions CI.
https://laravel.com/docs/master/releases#support-policy
Seeing #129 CIs failing, I created it as another PR.
> Shortcut stories and GitHub issues (delete irrelevant)
=> Fixing PHP versions of Actions CI in Laravel 6 and 7.

composer.json
Users on PHP 8.0+ started getting deprecation notices:
> PHP Deprecated:  Rollbar\Payload\Level implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /app/vendor/rollbar/rollbar/src/Payload/Level.php on line 5
This was fixed in rollbar-php v3.1.0, so I bumped it and ran the test suite. It's showing green lights so... whoppeee let's go! 
- Fixes https://github.com/rollbar/rollbar-php-laravel/issues/120
- Related to https://github.com/rollbar/rollbar-php/issues/555
=> Bump to rollbar-php v3.1.0 for PHP 8.0 compat

.github/workflows/ci-2.x.yml, .github/workflows/ci-4.x.yml
This PR fixes the failing CI on v2 and v4 branches. The reason the scheduled CI has been failing is that the `master` branch is being checked out. This fixes it so that we are checking out the respective v2 and v4 branches instead.
=> Fixed v2 and v4 scheduled CI checks out master branch

.github/workflows/ci-2.x.yml, .github/workflows/ci-4.x.yml
This fixes a typo introduced in #133. `ref` should be a child of `with`.
None
=> Fixed typo in workflows 'ref' not child of 'with'

.github/workflows/ci.yml
Our CI tests are failing because composer is trying to only install **stable** dependencies. Installing `rollbar/rollbar-laravel` from our a path repository without any version in the `composer.json` file [causes composer to assume its version is `dev-master`](https://getcomposer.org/doc/05-repositories.md#path). `dev-master` has a stability of `dev`.
To fix this problem I added an arbitrary stable version `1.0.0` to the `rollbar/rollbar-laravel` package in the test app `composer.json` file.
The other option would be to change the minimum stability requirement in the test app to `dev`. However, this could have some unintended side effects if other unstable packages are installed.
The last change is replacing the `Try to resolve requirements into an installable set of packages` step with …
=> Fixed required minimum stability causing the CI tests to fail

composer.json, src/MonologHandler.php
Updated the composer.json file to be inline with Laravel 10 - dropped all PHP support except 8.1 and added illuminate/support 10 only
=> BC - Updates for Laravel 10 and the MonologHandler

.github/workflows/ci.yml
This PR makes it so that our tests will run for the `master` branch. This is for the upcoming `v8.x` and above. Tests for the previous version `v7.x` of our Laravel package have been moved to the `ci-7.x.yml` file in #144.
To make the tests run we need to temporarily include the following lines in the install step.
```
composer config minimum-stability dev
composer config prefer-stable true
```
Once we release stable `v4.0.0` of the core `rollbar/rollbar` library, we can remove these two lines.
None
=> Updated the CI test workflow for v8 and Laravel 10

src/MonologHandler.php, src/RollbarServiceProvider.php, tests/RollbarTest.php
This PR does two things...
1. It adds missing type annotations and comments explaining the methods and their inputs and outputs. This is a BC because it must be respected by any user created class extending one of these.
2. It moves the `$access_token` in our test suite from being a dynamically declared property to being defined on the class for [compatibility with PHP 8.2](https://www.php.net/releases/8.2/en.php#deprecate_dynamic_properties).
None
=> Improved missing typing and comments

src/RollbarServiceProvider.php
We have not previously been sending the framework information to the Rollbar service. This updates the Rollbar config to include `laravel` and the version that is being used.
None
=> Added the missing 'framework' parameter to the Rollbar config.

.github/workflows/ci-7.x.yml
The scheduled tests for the [next/7.x/main](https://github.com/rollbar/rollbar-php-laravel/tree/next/7.x/main) branch are checking out the `master` branch. This fixes that.
None
=> Fixed the branch that is checked out when scheduled v7 tests run.

composer.json
With this merge request, it will add support for Laravel 11.
The only change that is needed for supporting Laravel 11 is allowing the Illuminate package to accept version 11.0 or higher.
I made this MR because I was already working with Laravel 11 (dev-master) and wanted to install this package as well, but was running into the issue that it's not supporting version 11.
After bumping the version inside a local installation, I ran all error logging command versions, and they were all added to Rollbar issue console.
> Don't know if you wanted to keep that PR template boilerplate, if so please let me know I can add it again :)
=> Added support for the illuminate/support package to also accept version 11

.github/workflows/ci.yml
This PR adds Laravel 11, PHP 8.3, and PHP 8.4 to the CI test suite.
None
=> Added Laravel 11, PHP 8.3, and PHP 8.4 to CI tests

.github/workflows/ci.yml, composer.json, phpunit.xml, src/RollbarServiceProvider.php, src/TelemetryListener.php, tests/RollbarTest.php, tests/TelemetryListenerTest.php, tests/TestCase.php
This PR adds support for telemetry to the Laravel package. There are a few notable items in this PR:
- This will be releases as a `beta` version since it depends on the Rollbar PHP core SDK `v4.1.0-rc`. Once the stable version of `v4.1` is released we will put out a stable release of this package.
- I updated how we handle configs to better support the additional configs for telemetry.
- The test suite was not being run in CI and needed some updates, in addition of telemetry tests.
This adds telemetry for three Laravel events to start with. We can add more as we see what is useful to the community. Each event type can be enabled or disabled individually. The events are:
- `MessageLogged`.
- `RouteMatched`.
- `QueryExecuted`.
The commit …
=> Added telemetry support

src/TelemetryListener.php, tests/TelemetryListenerTest.php
This resolves a bug in how log context is passed to telemetry. It moves the context to a `context` key in the extra data in the telemetry body.
Without this context array keys that also match telemetry body defined keys could throw type errors if the types don't match.
- Fix #171
=> Fixed #171 Log context passed directly to telemetry body.
